### PR TITLE
Upgrading features from bhanu

### PR DESCRIPTION
**Pull request by bhanuprasadChesetti**
Hello SHiva,
I done upgradations.
Please pull in my requests.

### CODE REVIEW

**Comment by sivasankargomasani** [comment]
Arey bro,
what did you do ?

**Comment by bhanuprasadChesetti** [comment]
Can't you see

**Comment by bhanuprasadChesetti** [comment]
hello

**Comment by sivasankargomasani** [comment]
Hi men

**Comment by sivasankargomasani** [comment]
resolve conflicts

**Comment by bhanuprasadChesetti** [comment]
i did it

**Comment by sivasankargomasani** [comment]
Hello Merged

**Comment by sivasankargomasani** [comment]
bye

**Comment by bhanuprasadChesetti** [comment]
ok see you

**Pull request merged**
